### ISSUE TITLE
Giving the possibility not to use an auxiliary Python file

### ISSUE THREAD

**Issue by spe-nsi** [swirly/pythonexec.js#4]
Is it possible to include a small Python code (say, 1 line) without having to create a file for this purpose ?

**Comment by swirly** [comment]
Resolved in master with commit aa120967e7925209914a07fe92e9b8f40db60e8b
Now, any block can use a file with the "data-file" tag
And python can use a file with data-python tag, or can be inline if data-python is not given or empty
